swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /tabla_posicion/:
    get:
      tags:
      - tabla_posicion
      description: get TablaPosicion
      operationId: TablaPosicionController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TablaPosicion'
        "404":
          description: not found resource
    post:
      tags:
      - tabla_posicion
      description: create TablaPosicion
      operationId: TablaPosicionController.Post
      parameters:
      - in: body
        name: body
        description: body for TablaPosicion content
        required: true
        schema:
          $ref: '#/definitions/models.TablaPosicion'
      responses:
        "201":
          description: '{int} models.TablaPosicion'
        "400":
          description: the request contains incorrect syntax
  /tabla_posicion/{id}:
    get:
      tags:
      - tabla_posicion
      description: get TablaPosicion by id
      operationId: TablaPosicionController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TablaPosicion'
        "404":
          description: not found resource
    put:
      tags:
      - tabla_posicion
      description: update the TablaPosicion
      operationId: TablaPosicionController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for TablaPosicion content
        required: true
        schema:
          $ref: '#/definitions/models.TablaPosicion'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TablaPosicion'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - tabla_posicion
      description: delete the TablaPosicion
      operationId: TablaPosicionController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
definitions:
  models.TablaPosicion:
    title: TablaPosicion
    type: object
    properties:
      Empatados:
        type: number
        format: double
      EquipoId:
        type: integer
        format: int64
      Ganados:
        type: number
        format: double
      Id:
        type: integer
        format: int64
      Jugados:
        type: number
        format: double
      Perdidos:
        type: number
        format: double
      Posicion:
        type: number
        format: double
      Puntos:
        type: number
        format: double
tags:
- name: tabla_posicion
  description: |
    TablaPosicionController operations for TablaPosicion
